/*
 Navicat Premium Data Transfer

 Source Server         : 测试
 Source Server Type    : MySQL
 Source Server Version : 50725
 Source Host           : daily.db.hasor.net:3306
 Source Schema         : example

 Target Server Type    : MySQL
 Target Server Version : 50725
 File Encoding         : 65001

 Date: 14/05/2020 16:15:44
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for interface_release
-- ----------------------------
DROP TABLE IF EXISTS `interface_release`;
CREATE TABLE `interface_release`  (
  `pub_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Publish ID',
  `pub_api_id` int(11) NOT NULL COMMENT '所属API ID',
  `pub_method` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'HttpMethod：GET、PUT、POST',
  `pub_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '拦截路径',
  `pub_status` int(2) NOT NULL COMMENT '状态：0有效，1无效（可能被下线）',
  `pub_type` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '脚本类型：SQL、DataQL',
  `pub_script` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '查询脚本：xxxxxxx',
  `pub_script_ori` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '原始查询脚本，仅当类型为SQL时不同',
  `pub_schema` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '接口的请求/响应数据结构',
  `pub_sample` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '请求/响应/请求头样本数据',
  `pub_option` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '扩展配置信息',
  `pub_release_time` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间（下线不更新）',
  PRIMARY KEY (`pub_id`) USING BTREE,
  INDEX `idx_interface_release`(`pub_api_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 67 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Dataway API 发布历史。' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of interface_release
-- ----------------------------
INSERT INTO `interface_release` VALUES (1, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (2, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (3, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (4, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (5, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (6, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (7, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (8, 1, 'GET', '/demos/db/databases/', 1, 'DataQL', 'select * from a;', NULL, '{}', '{\n\"requestBody\": \'{\"abc\":1111}\',\n                    \"headerData\": [\n                        {\"checked\": true, \"name\": \"name1\", \"value\": \"value1\"},\n                        {\"checked\": false, \"name\": \"name2\", \"value\": \"value2\"},\n                        {\"checked\": false, \"name\": \"name3\", \"value\": \"value3\"},\n                        {\"checked\": true, \"name\": \"name4\", \"value\": \"value4\"},\n                        {\"checked\": true, \"name\": \"name5\", \"value\": \"value5\"}\n                    ]\n}', NULL, '2020-03-24 12:52:13');
INSERT INTO `interface_release` VALUES (9, 1, 'PUT', '/demos/db/databases/', 1, 'SQL', 'show databases;', NULL, '{}', '{\"requestBody\":\"{\\\"abc\\\":1212}\",\"headerData\":[{\"name\":\"name111\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-03-24 23:27:26');
INSERT INTO `interface_release` VALUES (10, 1, 'PUT', '/demos/db/databases/', 1, 'SQL', 'var tempCall = @@inner_dataway_sql(`abc`)<%show databases;%>;\nreturn tempCall(${abc});', 'show databases;', '{}', '{\"requestBody\":\"{\\\"abc\\\":1212}\",\"headerData\":[{\"name\":\"name111\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-03-25 00:15:12');
INSERT INTO `interface_release` VALUES (11, 1, 'PUT', '/demos/db/databases/', 1, 'SQL', 'var tempCall = @@inner_dataway_sql(`abc`)<%show databases;%>;\nreturn tempCall(${abc});', 'show databases;', '{}', '{\"requestBody\":\"{\\\"abc\\\":1212}\",\"headerData\":[{\"name\":\"name111\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-03-25 00:17:20');
INSERT INTO `interface_release` VALUES (12, 1, 'PUT', '/demos/db/databases/', 1, 'SQL', 'var tempCall = @@inner_dataway_sql(`abc`)<%select :abc;%>;\nreturn tempCall(${abc});', 'select :abc;', '{}', '{\"requestBody\":\"{\\\"abc\\\":1212}\",\"headerData\":[{\"name\":\"name111\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-03-25 00:22:41');
INSERT INTO `interface_release` VALUES (13, 1, 'PUT', '/demos/db/databases/', 1, 'SQL', 'var tempCall = @@inner_dataway_sql(`apiId`)<%select * from interface_release where pub_api_id= :apiId order by pub_release_time desc limit 10;%>;\nreturn tempCall(${apiId});', 'select * from interface_release where pub_api_id= :apiId order by pub_release_time desc limit 10;', '{}', '{\"requestBody\":\"{\\\"apiId\\\":1}\",\"headerData\":[{\"name\":\"name111\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-03-25 00:26:32');
INSERT INTO `interface_release` VALUES (14, 14, 'POST', '/api/as', 1, 'DataQL', '// a new DataQL Query.\nreturn ${message};\nreturn abc', '// a new DataQL Query.\nreturn ${message};\nreturn abc', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[{\"name\":\"aa\",\"checked\":true,\"value\":\"a\"}]}', NULL, '2020-03-25 11:03:14');
INSERT INTO `interface_release` VALUES (15, 14, 'POST', '/api/as', 1, 'DataQL', '// a new DataQL Query.\nreturn ${message};', '// a new DataQL Query.\nreturn ${message};', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[{\"name\":\"aa\",\"checked\":true,\"value\":\"a\"}]}', NULL, '2020-03-25 13:56:17');
INSERT INTO `interface_release` VALUES (16, 14, 'POST', '/api/as', 1, 'DataQL', '// a new DataQL Query.\nreturn ${message};', '// a new DataQL Query.\nreturn ${message};', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[{\"name\":\"aa\",\"checked\":true,\"value\":\"a\"}]}', NULL, '2020-03-25 14:00:23');
INSERT INTO `interface_release` VALUES (17, 19, 'POST', '/api/asd/', 1, 'DataQL', '// a new DataQL Query.\nreturn [${message},message];', '// a new DataQL Query.\nreturn [${message},message];', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-03-25 17:01:17');
INSERT INTO `interface_release` VALUES (18, 19, 'POST', '/api/asd/', 1, 'DataQL', '// a new DataQL Query.\nreturn [${message},message];', '// a new DataQL Query.\nreturn [${message},message];', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-03-27 12:49:37');
INSERT INTO `interface_release` VALUES (19, 15, 'POST', '/tables', 1, 'DataQL', 'var tables = @@sql_exec[](arg,sss)<% \n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', 'var tables = @@sql_exec[](arg,sss)<% \n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', '{}', '{\"requestBody\":\"{}\",\"headerData\":[]}', NULL, '2020-03-29 00:29:57');
INSERT INTO `interface_release` VALUES (20, 15, 'POST', '/tables', 1, 'DataQL', 'var tables = @@sql[](arg,sss)<% \n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', 'var tables = @@sql[](arg,sss)<% \n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', '{}', '{\"requestBody\":\"{}\",\"headerData\":[]}', NULL, '2020-03-29 14:29:17');
INSERT INTO `interface_release` VALUES (21, 19, 'POST', '/api/asd/', 1, 'DataQL', 'import \'net.hasor.dataql.fx.basic.CollectionUdfSource\' as collect;\n\nvar replaceInfo = @@sql[](arg)<% \n    replace into my_option (\n        `id`,\n        `key`,\n        `value`,\n        `desc`,\n        `create_time`,\n        `modify_time`\n    ) values (\n        #{arg.id},\n        #{arg.key},\n        #{arg.value},\n        #{arg.desc},\n        ${arg.createTime},\n        ${arg.modifyTime}\n    );\n%>\n\nvar newData = collect.map2list(${data}) => [\n    {\n        \"id\"        : key,\n        \"key\"       : key,\n        \"value\"     : value,\n        \"desc\"      : (key + \" value is \" + value),\n        \"createTime\": \"now()\",\n        \"modifyTime\": \"now()\"\n    }\n]\n\nreturn replaceInfo(newData);', 'import \'net.hasor.dataql.fx.basic.CollectionUdfSource\' as collect;\n\nvar replaceInfo = @@sql[](arg)<% \n    replace into my_option (\n        `id`,\n        `key`,\n        `value`,\n        `desc`,\n        `create_time`,\n        `modify_time`\n    ) values (\n        #{arg.id},\n        #{arg.key},\n        #{arg.value},\n        #{arg.desc},\n        ${arg.createTime},\n        ${arg.modifyTime}\n    );\n%>\n\nvar newData = collect.map2list(${data}) => [\n    {\n        \"id\"        : key,\n        \"key\"       : key,\n        \"value\"     : value,\n        \"desc\"      : (key + \" value is \" + value),\n        \"createTime\": \"now()\",\n        \"modifyTime\": \"now()\"\n    }\n]\n\nreturn replaceInfo(newData);', '{}', '{\"requestBody\":\"{\\n  \\\"data\\\": {\\n    \\\"key1\\\": \\\"value1\\\",\\n    \\\"key2\\\": \\\"value2\\\",\\n    \\\"key3\\\": \\\"value3\\\"\\n  }\\n}\",\"headerData\":[]}', NULL, '2020-03-29 14:38:45');
INSERT INTO `interface_release` VALUES (22, 15, 'POST', '/tables', 1, 'DataQL', 'var tables = @@sql[](arg,sss)<%\n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', 'var tables = @@sql[](arg,sss)<%\n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', '{}', '{\"requestBody\":\"{}\",\"headerData\":[]}', NULL, '2020-03-29 23:38:21');
INSERT INTO `interface_release` VALUES (23, 20, 'POST', '/api/headerTools_codec', 0, 'DataQL', 'import \"net.hasor.dataql.fx.web.HeaderUdfSource\" as headerTools;\nimport \"net.hasor.dataql.fx.basic.CodecUdfSource\" as codec;\n\nreturn [\n    codec.stringMD5(\"\"),\n    codec.byteToHex(codec.stringToByte(\"你好中国。\",\"utf-8\")),\n    codec.byteToString(codec.hexToByte(\"E4BDA0E5A5BDE4B8ADE59BBDE38082\"),\"utf-8\"),\n    headerTools.map()\n];', 'import \"net.hasor.dataql.fx.web.HeaderUdfSource\" as headerTools;\nimport \"net.hasor.dataql.fx.basic.CodecUdfSource\" as codec;\n\nreturn [\n    codec.stringMD5(\"\"),\n    codec.byteToHex(codec.stringToByte(\"你好中国。\",\"utf-8\")),\n    codec.byteToString(codec.hexToByte(\"E4BDA0E5A5BDE4B8ADE59BBDE38082\"),\"utf-8\"),\n    headerTools.map()\n];', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[{\"name\":\"abc\",\"checked\":true,\"value\":\"aaa\"}]}', NULL, '2020-03-29 23:38:49');
INSERT INTO `interface_release` VALUES (24, 21, 'POST', '/api/@@sql', 0, 'DataQL', 'var tables = @@sql[](arg,sss)<%\n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', 'var tables = @@sql[](arg,sss)<%\n    select \n        #{arg.abc}  as a,\n        ${arg.bcd}  as b,\n        #{sss.a}    as c\n%>\n\nvar paramMap = {\n    \"abc\": \"now()\",\n    \"bcd\": \"now()\"\n}\nreturn tables(\n    [paramMap,paramMap],\n    [{\"a\":1} ,{\"a\":2} ]\n);', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-03-30 14:04:22');
INSERT INTO `interface_release` VALUES (25, 22, 'POST', '/api/my_option', 0, 'DataQL', 'import \'net.hasor.dataql.fx.basic.CollectionUdfSource\' as collect;\nimport \'net.hasor.dataql.fx.db.TransactionUdfSource\' as tran;\n\nvar replaceInfo = @@sql[](arg)<% \n    replace into my_option (\n        `id`,\n        `key`,\n        `value`,\n        `desc`,\n        `create_time`,\n        `modify_time`\n    ) values (\n        #{arg.id},\n        #{arg.key},\n        #{arg.value},\n        #{arg.desc},\n        now(),\n        now()\n    );\n%>\n\nvar newData = collect.map2list(${data}) => [\n    {\n        \"id\"        : key,\n        \"key\"       : key,\n        \"value\"     : value,\n        \"desc\"      : (key + \" value is \" + value),\n        \"createTime\": \"now()\",\n        \"modifyTime\": \"now()\"\n    }\n]\n\nreturn tran.required(() -> {\n    return replaceInfo(newData);\n});\n', 'import \'net.hasor.dataql.fx.basic.CollectionUdfSource\' as collect;\nimport \'net.hasor.dataql.fx.db.TransactionUdfSource\' as tran;\n\nvar replaceInfo = @@sql[](arg)<% \n    replace into my_option (\n        `id`,\n        `key`,\n        `value`,\n        `desc`,\n        `create_time`,\n        `modify_time`\n    ) values (\n        #{arg.id},\n        #{arg.key},\n        #{arg.value},\n        #{arg.desc},\n        now(),\n        now()\n    );\n%>\n\nvar newData = collect.map2list(${data}) => [\n    {\n        \"id\"        : key,\n        \"key\"       : key,\n        \"value\"     : value,\n        \"desc\"      : (key + \" value is \" + value),\n        \"createTime\": \"now()\",\n        \"modifyTime\": \"now()\"\n    }\n]\n\nreturn tran.required(() -> {\n    return replaceInfo(newData);\n});\n', '{}', '{\"requestBody\":\"{\\n  \\\"data\\\": {\\n    \\\"key1\\\": \\\"value1\\\",\\n    \\\"key2\\\": \\\"value2\\\",\\n    \\\"key3\\\": \\\"value3\\\"\\n  }\\n}\",\"headerData\":[]}', NULL, '2020-03-30 14:05:41');
INSERT INTO `interface_release` VALUES (26, 25, 'GET', '/api/demos', 0, 'DataQL', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn query()', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn query()', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-04-14 14:51:48');
INSERT INTO `interface_release` VALUES (27, 26, 'POST', '/api/demos/find_user_by_name', 0, 'DataQL', '// a new DataQL Query.\nvar queryUser = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>\n\nreturn queryUser(${userName}) => [\n    {\n        \"user_id\" : id,\n        \"user_name\" : name,\n        \"user_sex\" : sex\n    }\n]', '// a new DataQL Query.\nvar queryUser = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>\n\nreturn queryUser(${userName}) => [\n    {\n        \"user_id\" : id,\n        \"user_name\" : name,\n        \"user_sex\" : sex\n    }\n]', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-16 14:58:57');
INSERT INTO `interface_release` VALUES (28, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'SQL', 'var tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', '    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:54:02');
INSERT INTO `interface_release` VALUES (29, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', 'var tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:56:26');
INSERT INTO `interface_release` VALUES (30, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn ${userName};\nreturn tempCall(${userName});', 'var tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn ${userName};\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:56:58');
INSERT INTO `interface_release` VALUES (31, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:59:22');
INSERT INTO `interface_release` VALUES (32, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',${userName},\'%\')\n%>;\nreturn tempCall(${userName});', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',${userName},\'%\')\n%>;\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:59:44');
INSERT INTO `interface_release` VALUES (33, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 09:59:57');
INSERT INTO `interface_release` VALUES (34, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName[0]},\'%\')\n%>;\nreturn tempCall(${userName});', 'var tempCall = @@sql(userName)<%    select * from user_info where `name` like concat(\'%\',#{userName[0]},\'%\')\n%>;\nreturn tempCall(${userName});', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:03:14');
INSERT INTO `interface_release` VALUES (35, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'SQL', 'var tempCall = @@sql(`userName`)<%select * from user_info where `name` like concat(\'%\',#{userName[0]},\'%\')%>;\nreturn tempCall(${userName});', 'select * from user_info where `name` like concat(\'%\',#{userName[0]},\'%\')', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:03:35');
INSERT INTO `interface_release` VALUES (36, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'DataQL', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:13:26');
INSERT INTO `interface_release` VALUES (37, 28, 'POST', '/api/demos/find_user_by_name_post', 0, 'DataQL', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:14:06');
INSERT INTO `interface_release` VALUES (38, 28, 'POST', '/api/demos/find_user_by_name_post', 0, 'DataQL', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', 'var fourceOne = (mabeArray) -> {\n    var tmpUserName = ${userName} => [ # ]\n    return tmpUserName[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:14:20');
INSERT INTO `interface_release` VALUES (39, 28, 'POST', '/api/demos/find_user_by_name_post', 0, 'DataQL', 'var fourceOne = (mabeArray) -> {\n    var tmpVar = mabeArray => [ # ]\n    return tmpVar[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', 'var fourceOne = (mabeArray) -> {\n    var tmpVar = mabeArray => [ # ]\n    return tmpVar[0]\n}\n\n\nvar tempCall = @@sql(`userName`)<%    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>;\nreturn tempCall(\n    fourceOne(${userName})\n);', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 10:17:37');
INSERT INTO `interface_release` VALUES (40, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'SQL', 'var tempCall = @@sql(`userName`)<%select * from user_info where `name` like concat(\'%\',#{userName},\'%\')%>;\nreturn tempCall(${userName});', 'select * from user_info where `name` like concat(\'%\',#{userName},\'%\')', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-17 22:42:11');
INSERT INTO `interface_release` VALUES (41, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-04-20 12:25:32');
INSERT INTO `interface_release` VALUES (42, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'SQL', 'var tempCall = @@sql(`userName`)<%select * from user_info where `name` like concat(\'%\',#{userName},\'%\')%>;\nreturn tempCall(${userName});', 'select * from user_info where `name` like concat(\'%\',#{userName},\'%\')', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"2\\\"}\",\"headerData\":[]}', NULL, '2020-04-23 11:56:44');
INSERT INTO `interface_release` VALUES (43, 30, 'POST', '/api/demos/self', 0, 'DataQL', '// a new DataQL Query.\nreturn ${self};', '// a new DataQL Query.\nreturn ${self};', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-04-23 11:57:25');
INSERT INTO `interface_release` VALUES (44, 17, 'POST', '/demos/mock', 0, 'DataQL', 'return {\n    \"success\":true,\n    \"code\":0,\n    \"executionTime\":10,\n    \"value\":{\n        \"msg\":\"abcdefg\",\n        \"select\":{\n            \"abcdefg\":\"abcdefg\",\n            \"now\":1583202623000\n        },\n        \"data\":[\n            \"biz_resumption_staff\",\n            \"interface_ql\",\n            \"my_option\"\n        ]\n    },\n    \"message\":\"OK\"\n}', 'return {\n    \"success\":true,\n    \"code\":0,\n    \"executionTime\":10,\n    \"value\":{\n        \"msg\":\"abcdefg\",\n        \"select\":{\n            \"abcdefg\":\"abcdefg\",\n            \"now\":1583202623000\n        },\n        \"data\":[\n            \"biz_resumption_staff\",\n            \"interface_ql\",\n            \"my_option\"\n        ]\n    },\n    \"message\":\"OK\"\n}', '{}', '{}', NULL, '2020-04-23 14:21:07');
INSERT INTO `interface_release` VALUES (45, 26, 'POST', '/api/demos/find_user_by_name', 0, 'DataQL', '// a new DataQL Query.\nvar queryUser = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>\n\nreturn [\n    ${self},\n    queryUser(${userName}) => [\n        {\n            \"user_id\" : id,\n            \"user_name\" : name,\n            \"user_sex\" : sex\n        }\n    ]\n]', '// a new DataQL Query.\nvar queryUser = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\')\n%>\n\nreturn [\n    ${self},\n    queryUser(${userName}) => [\n        {\n            \"user_id\" : id,\n            \"user_name\" : name,\n            \"user_sex\" : sex\n        }\n    ]\n]', '{}', '{\"requestBody\":\"{\\\"userName\\\":\\\"1\\\"}\",\"headerData\":[]}', NULL, '2020-04-26 21:36:15');
INSERT INTO `interface_release` VALUES (46, 31, 'GET', '/api/test/get', 1, 'SQL', 'var tempCall = @@sql(`message`)<%-- a new Query.\nselect #{message};%>;\nreturn tempCall(${message});', '-- a new Query.\nselect #{message};', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-04-30 18:44:05');
INSERT INTO `interface_release` VALUES (47, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-04 23:46:12');
INSERT INTO `interface_release` VALUES (48, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-04 23:53:32');
INSERT INTO `interface_release` VALUES (49, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-05 00:12:28');
INSERT INTO `interface_release` VALUES (50, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-05 00:12:53');
INSERT INTO `interface_release` VALUES (51, 4, 'PUT', '/demos/user/user-list/', 0, 'DataQL', 'throw 300 ,\"aaaa\"', 'throw 300 ,\"aaaa\"', '{}', '{\"requestBody\":\"{\\\"abc\\\":4444}\",\"headerData\":[{\"name\":\"name1\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-05-05 00:13:36');
INSERT INTO `interface_release` VALUES (52, 4, 'PUT', '/demos/user/user-list/', 0, 'DataQL', 'throw 300 ,\"aaaa\"', 'throw 300 ,\"aaaa\"', '{}', '{\"requestBody\":\"{\\\"abc\\\":4444}\",\"headerData\":[{\"name\":\"name1\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', NULL, '2020-05-05 00:13:51');
INSERT INTO `interface_release` VALUES (53, 32, 'ANY', '/api/demos/any', 1, 'DataQL', '// a new Query.\nreturn ${message};', '// a new Query.\nreturn ${message};', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', NULL, '2020-05-05 10:51:02');
INSERT INTO `interface_release` VALUES (54, 30, 'POST', '/api/demos/self', 0, 'SQL', 'var tempCall = @@sql(`message`)<%// a new DataQL Query.sw\nreturn ${self};%>;\nreturn tempCall(${message});', '// a new DataQL Query.sw\nreturn ${self};', '{}', '{\"requestBody\":\"{\\n  \\\"message\\\": \\\"Hello DataQL.\\\"\\n}\",\"headerData\":[]}', NULL, '2020-05-06 20:45:46');
INSERT INTO `interface_release` VALUES (55, 33, 'GET', '/api/demos/page_query_get', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-07 18:32:33');
INSERT INTO `interface_release` VALUES (56, 33, 'GET', '/api/demos/page_query_get', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : (${pageNumber} - 1)  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : (${pageNumber} - 1)  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', NULL, '2020-05-07 18:34:11');
INSERT INTO `interface_release` VALUES (57, 29, 'POST', '/api/demos/page_query', 0, 'DataQL', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '// 步骤 1：定义分页SQL\nhint FRAGMENT_SQL_QUERY_BY_PAGE = true\nvar dimSQL = @@sql(userName)<%\n    select * from user_info where `name` like concat(\'%\',#{userName},\'%\') order by id asc\n%>;\n\n// 步骤 2：获取分页对象\nvar queryPage = dimSQL(${userName});\n\n// 步骤 3：设置分页信息 \nrun queryPage.setPageInfo({\n    \"pageSize\"    : 5, // 页大小\n    \"currentPage\" : ${pageNumber}  // 第3页\n});\n\nreturn {\n    \"pageInfo\" : queryPage.pageInfo(),\n    \"pageData\" : queryPage.data()\n}', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"\\\",\\n  \\\"pageNumber\\\": 1\\n}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-12 10:24:53');
INSERT INTO `interface_release` VALUES (58, 25, 'GET', '/api/demos', 0, 'DataQL', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn [query(),${message}]', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn [query(),${message}]', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-12 10:26:40');
INSERT INTO `interface_release` VALUES (59, 25, 'GET', '/api/demos', 0, 'DataQL', 'var query = @@sql()<%\n    select api_id from interface_info\n%>\nreturn [query(),${message}]', 'var query = @@sql()<%\n    select api_id from interface_info\n%>\nreturn [query(),${message}]', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-12 10:27:15');
INSERT INTO `interface_release` VALUES (60, 27, 'GET', '/api/demos/find_user_by_name_get', 0, 'SQL', 'var tempCall = @@sql(`userName`)<%select * from user_info where `name` like concat(\'%\',#{userName},\'%\')%>;\nreturn tempCall(${userName});', 'select * from user_info where `name` like concat(\'%\',#{userName},\'%\')', '{}', '{\"requestBody\":\"{\\n  \\\"userName\\\": \\\"2\\\"\\n}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-13 13:19:13');
INSERT INTO `interface_release` VALUES (61, 5, 'PUT', '/demos/user/add-user/', 1, 'SQL', 'var tempCall = @@sql(`abc`)<%select * from a;%>;\nreturn tempCall(${abc});', 'select * from a;', '{}', '{\"requestBody\":\"{\\\"abc\\\":false}\",\"headerData\":[{\"name\":\"name1\",\"checked\":true,\"value\":\"value1\"},{\"name\":\"name2\",\"checked\":false,\"value\":\"value2\"},{\"name\":\"name3\",\"checked\":false,\"value\":\"value3\"},{\"name\":\"name4\",\"checked\":true,\"value\":\"value4\"},{\"name\":\"name5\",\"checked\":true,\"value\":\"value5\"}]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-13 13:25:09');
INSERT INTO `interface_release` VALUES (62, 34, 'POST', '/api/demoss', 0, 'SQL', 'var tempCall = @@sql(`api_id`)<%-- a new Query.\nselect * from interface_info;%>;\nreturn tempCall(${api_id});', '-- a new Query.\nselect * from interface_info;', '{}', '{\"requestBody\":\"{\\n  \\\"api_id\\\": \\\"12\\\"\\n}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-14 13:27:01');
INSERT INTO `interface_release` VALUES (63, 25, 'GET', '/api/demos', 0, 'DataQL', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn [query(),${message}]', 'var query = @@sql()<%\n    select * from interface_info\n%>\nreturn [query(),${message}]', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-14 13:30:14');
INSERT INTO `interface_release` VALUES (64, 36, 'POST', '/api/test123', 1, 'SQL', 'var tempCall = @@sql(`message`)<%-- a new Query.\nselect * from user_info;%>;\nreturn tempCall(${message});', '-- a new Query.\nselect * from user_info;', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-14 15:53:26');
INSERT INTO `interface_release` VALUES (65, 36, 'POST', '/api/test123', 1, 'SQL', 'var tempCall = @@sql(`message`)<%-- a new Query.\nselect * from user_info;%>;\nreturn tempCall(${message});', '-- a new Query.\nselect * from user_info;', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-14 15:55:18');
INSERT INTO `interface_release` VALUES (66, 36, 'POST', '/api/test123', 0, 'SQL', 'var tempCall = @@sql(`message`)<%-- a new Query.\nselect * from user_info;%>;\nreturn tempCall(${message});', '-- a new Query.\nselect * from user_info;', '{}', '{\"requestBody\":\"{\\\"message\\\":\\\"Hello DataQL.\\\"}\",\"headerData\":[]}', '{\"resultStructure\":true,\"responseFormat\":\"{\\n  \\\"success\\\"      : \\\"@resultStatus\\\",\\n  \\\"message\\\"      : \\\"@resultMessage\\\",\\n  \\\"code\\\"         : \\\"@resultCode\\\",\\n  \\\"lifeCycleTime\\\": \\\"@timeLifeCycle\\\",\\n  \\\"executionTime\\\": \\\"@timeExecution\\\",\\n  \\\"value\\\"        : \\\"@resultData\\\"\\n}\"}', '2020-05-14 16:00:59');

SET FOREIGN_KEY_CHECKS = 1;
